env:
  	browser: true
  	es2021: true
	node: true
extends: eslint:recommended
overrides: []
parserOptions:
	sourceType: module
  	ecmaVersion: latest
rules:
  	indent:
		- error
		- tab
  	linebreak-style:
		- error
		- unix
  	quotes:
		- error
		- single
  	semi:
		- error
		- never